### ISSUE TITLE
docker image does not create/seed sqlite database out of the box

### ISSUE THREAD

**Issue by pniederlag** [DiUS/pact_broker-docker#102]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [X] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [X] Upgraded to the latest Pact Broker Docker image OR
* [x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [X] Read the [Troubleshooting](https://github.com/DiUS/pact_broker-docker/wiki/Troubleshooting) page

## Expected behaviour

```docker run --name=packt-broker --rm -ti -e PACT_BROKER_DATABASE_ADAPTER=sqlite -e PACT_BROKER_DATABASE_NAME=test.sqlite docker.io/dius/pact-broker```

Should start a docker container that ist just usable right away

## Actual behaviour

* The user runs into a lot of error messages
* The database is *not* created

## Steps to reproduce

use above docker run command

To get it running:

* use PACT_BROKER_DATABASE_NAME=db/test.sqlite
* docker exec into the container and create the directory db und chown it to app:app

**Comment by bethesque** [comment]
Sqlite is only to be used inside the container for demo purposes. There is no production use case for this scenario. Try putting the database in the /tmp directory, as the home directory is probably not writeable for security purposes.

**Comment by pniederlag** [comment]
thx for your feedback @bethesque 

I understand the container is intended for production use and certainly sqlite is not meant to be used in production environments.

please consider also people using this image for evaluation purposes, where sqlite in general is a pretty good choice as it requires way less work for setup und persistence, performance and alike are neglectible when spinning up a container for a quick glance.

If the container is not be used for evaluation or simple out-of-the-box functionality in combination with sqlite it would be advisable to indicate this in the README. Would maybe save some others folks some time spent in debugging/analysis ;)

**Comment by bethesque** [comment]
I think most people use the docker-compose file, or mount a directory from a local volume, which is why this hasn't come up before. I've seen your note for an update in the readme, thanks.
