### ISSUE TITLE
version 2.88.0.0 doesn't use value of PACT_BROKER_DATABASE_PORT 

### ISSUE THREAD

**Issue by dpittner** [DiUS/pact_broker-docker#110]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x] Upgraded to the latest Pact Broker Docker image OR
* [x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x] Read the [Troubleshooting](https://github.com/DiUS/pact_broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** 2.88.0.0
* **pact-broker docker version:** 2.88.0.0
* **OS**: Ubuntu 20.10
* **pact broker client details:** n/a

## Expected behaviour

PACT_BROKER_DATABASE_PORT is taken into account when running broker as in previous version. 

## Actual behaviour

PACT_BROKER_DATABASE_PORT env variable is ignored and default port used. 

## Steps to reproduce

Configure broker to use a non-default PG DB port via env variable (as documented). Logs will show 5432 is used as port.

## Relevent log files

Probably related to this change: https://github.com/DiUS/pact_broker-docker/commit/59d23d9#diff-ffeeef8a141c9a892332934fa7599484bd11b96a3eada3a0557117ff524f86e5L144
Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
Fixed in 2.89.0. Please update to 2.89.0.0
