### ISSUE TITLE
Support mysql

### ISSUE THREAD

**Issue by yadavsaroj** [DiUS/pact_broker-docker#21]
Hi,

I was hoping to run pact_broker with mysql and would like to use your base image. However currently it supports only postgres. What do you think about supporting both postgres and mysql? fwict, [this code](https://github.com/DiUS/pact_broker-docker/blob/master/pact_broker/config.ru#L22) is the only one that is database dependent. 

Cheers!
Saroj

**Comment by bethesque** [comment]
Also the postgres gem here: https://github.com/DiUS/pact_broker-docker/blob/master/pact_broker/Gemfile#L4

The adapter could be set via an environment variable. We could add `gem "mysql2"` to the Gemfile as well, and hopefully there would not be any clash between them.

**Comment by bethesque** [comment]
Mysql is now supported.
