### ISSUE TITLE
Support other port than 80

### ISSUE THREAD

**Issue by wburgers** [DiUS/pact_broker-docker#24]
Only when mapping port 80 of the docker host to port 80 of the docker container will pact broker work.
This is not ideal, because at our company, we want to be able to run multiple services on a single docker host.
The host should be able to display a default page on port 80 that shows how to request a new service for example.
Not being able to set the port is not really workable.

**EDIT**
I didn't check the pull requests before creating this issue.
#17 looks promising.

I hope it can be merged...

**Comment by uglyog** [comment]
This issue has been fixed, and the latest image on docker hub should work.

**Comment by mefellows** [comment]
Can we close this then?
