### ISSUE TITLE
Error when starting pactbroker docker container

### ISSUE THREAD

**Issue by neilsyrett** [DiUS/pact_broker-docker#29]
I have installed and configured the PostgresSQL DB in a Docker container (pactbroker-db) as per the instructions in POSTGRESQL.md and created the pactbroker Docker container (pactbroker) but when I come to start the pactbroker I receive the following error.  Can you offer any advice?

$ docker start --attach pactbroker
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 346, in <module>
    main(args)
  File "/sbin/my_init", line 265, in main
    export_envvars()
  File "/sbin/my_init", line 88, in export_envvars
    f.write(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)

**Comment by notyy** [comment]
I have same problem. 
the last line is 
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-9: ordinal not in range(128)

any hint on how to solve this?

**Comment by pedrro** [comment]
Try to use the docker compose version: https://github.com/brancz/pact_broker_pg_docker
