### ISSUE TITLE
Add docker-compose

### ISSUE THREAD

**Issue by shashidesai** [DiUS/pact_broker-docker#30]
* Push pact-broker images to docker-hub.
* Add docker-compose file to the repo for better setup.

Just thought this would make the setup easier and if we had official images pushed to docker-hub.

**Comment by bethesque** [comment]
@mefellows , @uglyog, I'm so behind on docker. Is there someone in Dius who we can ask to do this?

**Comment by uglyog** [comment]
I'll be in on Monday, so I can look into doing this. Otherwise, someone on the bench could help.

**Comment by bethesque** [comment]
Will ask Leanne.

**Comment by shashidesai** [comment]
there are few docker images pushed by others onto docker-hub (https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=pact+broker&starCount=0) but if we had official images via pact-foundation, then it would be better.

**Comment by bethesque** [comment]
Isn't it this one? https://hub.docker.com/r/dius/pact_broker/

**Comment by shashidesai** [comment]
oops my bad, I meant images exist, but I think I had some issue with this image, so used some other repo which had docker-compose setup instructions which was easier and faster.

**Comment by bethesque** [comment]
Can you remember what the issues are so that we can fix them? Which one did you end up using?

**Comment by shashidesai** [comment]
@bethesque - It was probably my issue as I couldn't figure out setup instructions and I ended up using this repo as they had proper instructions using docker-compose (as we were using docker-compose for our project) I ended up using this repo - https://github.com/brancz/pact_broker_pg_docker

**Comment by mefellows** [comment]
I recall #24 being an issue, but that seems to be fixed now. I can probably take a look at this.
We can add a Docker compose file, it's very simple.

**Comment by shashidesai** [comment]
@mefellows - I have created a PR and attached the error I see when I try to use https://hub.docker.com/r/dius/pact_broker/ image.

**Comment by mefellows** [comment]
Thanks, as discussed, once the corrections have been made to the PR we'll bring in.

**Comment by shashidesai** [comment]
@mefellows - next time will try to do a better job at adding docs !

**Comment by mefellows** [comment]
No worries, and thanks again :)
