### ISSUE TITLE
Idiomatic port assigning

### ISSUE THREAD

**Issue by liamawhite** [DiUS/pact_broker-docker#33]
With the caveat that I'm completely new to ruby. How would I assign a non-default port in the `config.ru` using env vars?

```pg_user = ENV['PACT_BROKER_DATABASE_USERNAME']
pg_password = ENV['PACT_BROKER_DATABASE_PASSWORD']
pg_host = ENV['PACT_BROKER_DATABASE_HOST']
pg_port = ENV['PACT_BROKER_DATABASE_PORT']
pg_database = ENV['PACT_BROKER_DATABASE_NAME']

connection_string = "postgres://#{pg_user}:#{pg_password}@#{pg_host}:#{pg_port}/#{pg_database}"
puts "#{connection_string}"
```

Whenever I set a custom env var it isn't picked up and the code above prints
`postgres://user:password@host:/database` (without the port passed in via docker)

This may be some ruby nuance but I would expect to see a correctly formed url there, but any custom env var (not in the default `config.ru`) I use doesn't show up.

I have similar problems with the other issue I raised (#32) when trying to specify a `PACT_USERNAME` and  `PACT_PASSWORD` as env vars and try to use them in my `config.ru`

**Comment by bethesque** [comment]
You need to add it to container/etc/nginx/main.d/pactbroker-env.conf for it to be loaded into the nginx process.

**Comment by bethesque** [comment]
https://github.com/DiUS/pact_broker-docker/commit/72911145ccb54810fb8be0838560af91a2a83eb2
