### ISSUE TITLE
pact_broker Changes

### ISSUE THREAD

**Issue by itsmenandess** [DiUS/pact_broker-docker#39]
Hi,

Is this changes are updated in this pact_broker-docker project?
"https://github.com/DiUS/pact_broker-docker"

Changes in pact_broker:
https://github.com/pact-foundation/pact_broker/blob/master/CHANGELOG.md

Thanks

**Comment by mefellows** [comment]
Looks like we are two micro versions behind. (`2.0.2` vs `2.0.4`).

**Comment by itsmenandess** [comment]
Can i get latest update pact_broker-docker project?

**Comment by mefellows** [comment]
Just pushed an update, build should be up within the next ~30 mins or so (Docker Hub will do it automatically).
