### ISSUE TITLE
Pact broker images not versioned

### ISSUE THREAD

**Issue by stemlaur** [DiUS/pact_broker-docker#44]
The available images of https://hub.docker.com/r/dius/pact-broker/ are all tagged LATEST which makes impossible to rollback when a regression exists on a new version.

It would be nice to have a versions on docker hub to be able to have reproductible deployments of pact-broker.

**Comment by bethesque** [comment]
Good point, we'll add it to the script.

**Comment by bethesque** [comment]
Releases are now made using `script/release.sh`. This tags the docker image using the format `$PACT_BROKER_GEM_VERSION-$RELEASE`.

https://github.com/DiUS/pact_broker-docker/commit/c1b764ff270ebdd4e6a248474ab18228c13a7a40
