### ISSUE TITLE
Can't run the example with the provider docker-compose

### ISSUE THREAD

**Issue by MrOutis** [DiUS/pact_broker-docker#46]
This is the error:
```
Message from application: uninitialized constant PactBroker::Api::Resources::BaseResource (NameError)
```

**Comment by MrOutis** [comment]
I downgraded the image to the `2.4.0-2` and is working as expected.

**Comment by bethesque** [comment]
Ah, sorry. I fixed that ruby error in the gem, but need to push the latest docker image.

**Comment by MrOutis** [comment]
thanks, @bethesque, I'll close this, then.

**Comment by bethesque** [comment]
Hm. I'm a bit confused. 2.4.0-2 should BE the latest. It's after 2.4.0-1. Not sure what's going on with the tags.

**Comment by bethesque** [comment]
Oh, right. 2.4.*2*, not 2.4.*0*.

**Comment by bethesque** [comment]
I am able to run docker-compose up with the latest. Not sure why there is a difference, because the fix for that require was made before I released 2.4.2.

**Comment by MrOutis** [comment]
super weird, @bethesque, in my local machine is running correctly but running it on a Digital Ocean droplet (with Docker engine pre-installed + docker-compose as a container) is throwing the error.
Is running with the latest version, indeed.

**Comment by bethesque** [comment]
We've found some orchestrated environments, they don't refresh the "latest" if they already think they have the "latest". Try pulling it in by the named tag `2.4.2-2`.
