### ISSUE TITLE
Docker tag 'latest' does not point to latest version

### ISSUE THREAD

**Issue by dervism** [DiUS/pact_broker-docker#56]
The 'latest' tag needs to be updated to version 2.11.0-1. Currently it's behind:

https://hub.docker.com/r/dius/pact-broker/builds/

When running the Docker-Compose example, the startup fails. Setting the tag to 2.11.0-1 and everything runs ok:

```
broker_app:
    image: dius/pact-broker:2.11.0-1
```

**Comment by bethesque** [comment]
Thanks, I've fixed the regular expression in the build settings. I've released 2.12.0-1/latest.
