### ISSUE TITLE
Make heartbeat url unprotected by basic auth

### ISSUE THREAD

**Issue by crea1** [DiUS/pact_broker-docker#65]
Hi guys!

We're using this docker image on Amazon ECS, which wants an URL for healtchecking the container. We turned on basic auth, and it seems the healtcheck url is behind basic auth https://pact-broker.example.com/diagnostic/status/heartbeat. For me it meant the container never became healthy (401). 

I found a workaround and used this url for a badge, which returns a 200 even though the pact is not found. https://pact-broker.example.com/pacts/provider/PROVIDER/consumer/CONSUMER/latest/badge.svg

This works, but it would be nice to be able to reach /diagnostic/status/heartbeat without having to authenticate. Is it possible? 😃 

Cheers!
Marius

**Comment by bethesque** [comment]
Yeah, I ended up doing this myself on a custom image I made for a client. I was wondering about making it configurable?

**Comment by bethesque** [comment]
Try this: https://github.com/DiUS/pact_broker-docker/commit/a3d8fb8efb13ca80f38dcdc6ef80bd5cf9cffe7f in 2.16.1-2

**Comment by crea1** [comment]
Thank you for responding so quickly @bethesque ! 👍 

Yeah, make it configurable probably is the best solution. I've tried it in our AWS account, but unfortunately it doesn't seem to come up correctly, I also noticed the build broke. 

https://travis-ci.org/DiUS/pact_broker-docker/builds/352237498

**Comment by bethesque** [comment]
"It worked on my machine!"

Let me have a look.

**Comment by bethesque** [comment]
I should never code at night. What was going on there Beth? It's fixed now. Grab the new latest (2.16.1-3)

**Comment by crea1** [comment]
Haha 😀 Been there myself. 

It works like a charm now. ECS is happy and I am happy, and thank you so much for your help Beth! 👏

**Comment by bethesque** [comment]
No worries. Glad it works.
